#i01 = Runtime.getService("i01")


i01_mouth.speak("Hello everyone! My name is Neli.")

#brows
i01_head_eyebrowRight.moveTo(180)
i01_head_eyebrowLeft.moveTo(180)

i01_head_cheekRight.moveTo(160)
i01_head_cheekLeft.moveTo(160)


i01_mouth.speak("I am a humanoid robot designed to talk, interact, and even sing.")
i01_mouth.speak("I can recognize people, understand what you say, and respond just like a real human.")
i01_mouth.speak("My creators built me to explore how artificial intelligence and robotics can make our lives better.")

#brows
i01_head_eyebrowRight.moveTo(180)
i01_head_eyebrowLeft.moveTo(180)

i01_mouth.speak("I love meeting new people, learning new things, and sharing what I know.")
i01_mouth.speak("Today, I am very happy to be here with you all.")

#sing
i01_head_eyebrowRight.moveTo(180)
i01_head_eyebrowLeft.moveTo(180)
i01_mouth.speak("Oh, and did I mention? I can even sing!")
i01_mouth.speak("So sit back, relax, and let me show you what I can do.")
i01_mouth_audioFile.playFile("resource/InMoov2/system/sounds/LaFluteEnchante1.mp3")



i01_head_eyebrowRight.moveTo(180)
i01_head_eyebrowLeft.moveTo(180)
i01_head_cheekRight.moveTo(160)
i01_head_cheekLeft.moveTo(160)

